apiVersion: v2
name: danbooru-stack
description: An unofficial helm chart for the entire danbooru stack.
maintainers:
  - name: my0n
home: https://github.com/my0n/helm-charts/tree/master/charts/danbooru-stack
sources:
  - https://github.com/my0n/helm-charts/tree/master/charts/danbooru-stack

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.3

dependencies:
  - name: danbooru
    version: 0.0.2
    repository: https://my0n.github.io/helm-charts
    condition: danbooru.enabled
  - name: iqdb
    version: 0.0.1
    repository: https://my0n.github.io/helm-charts
    condition: iqdb.enabled
  - name: postgresql
    version: 11.6.19
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.0.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
