apiVersion: v2
name: cloudcmd
description: An unofficial helm chart for cloudcmd.
maintainers:
  - name: my0n
home: https://github.com/my0n/helm-charts/tree/master/charts/cloudcmd
sources:
  - https://github.com/my0n/helm-charts/tree/master/charts/cloudcmd
  - https://github.com/coderaiser/cloudcmd

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "16.6.1"

dependencies:
  - name: common
    version: 4.3.0 # make sure to use the latest common library version available
    repository: https://library-charts.k8s-at-home.com
