{{- if contains "|" (.Values.backend.baseUrl | toString) }}
{{- fail "backend.baseUrl may not contain the pipe character '|'" }}
{{- end }}
{{- if contains "|" (.Values.backend.host | toString) }}
{{- fail "backend.host may not contain the pipe character '|'" }}
{{- end }}
{{- if contains "|" (.Values.backend.maxFileSize | toString) }}
{{- fail "backend.maxFileSize may not contain the pipe character '|'" }}
{{- end }}
{{- if contains "|" (.Values.backend.port | toString) }}
{{- fail "backend.port may not contain the pipe character '|'" }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "szurubooru-client.fullname" . }}
  labels:
    {{- include "szurubooru-client.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "szurubooru-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "szurubooru-client.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "szurubooru-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - '-cx'
            - |
              sed -i "s|client_max_body_size 1073741824;|client_max_body_size ${BACKEND_MAX_FILE_SIZE};|" /etc/nginx/nginx.conf
              sed -i "s|server __BACKEND__:6666;|server __BACKEND__:${BACKEND_PORT};|" /etc/nginx/nginx.conf
              exec /docker-start.sh
          env:
            - name: BACKEND_HOST
              value: {{ .Values.backend.host }}
            - name: BACKEND_MAX_FILE_SIZE
              value: {{ .Values.backend.maxFileSize | quote }}
            - name: BACKEND_PORT
              value: {{ .Values.backend.port | quote }}
            - name: BASE_URL
              value: {{ .Values.backend.baseUrl }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
