#
# IMPORTANT NOTE
#
# This chart inherits from the k8s@home library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/danbooru/danbooru
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# @default -- See values.yaml
args: ["bash", "-c", "bin/rails db:prepare && bin/rails db:seed && bin/rails server -b 0.0.0.0"]

# -- environment variables. See [image docs](https://docs.k8s-at-home.com/our-container-images/configuration/) for more details.
# @default -- See values.yaml
env:
  # RAILS_ENV: "production"
  # RAILS_SERVE_STATIC_FILES: "true"
  # PUMA_WORKERS: "1"
  # DATABASE_URL: "postgresql://danbooru@postgresql/danbooru"
  # DANBOORU_REDIS_URL: "redis://redis:6379"
  # DANBOORU_IQDB_URL: "http://iqdb:5588"
  # DANBOORU_CANONICAL_URL: "https://chart-example.local"

# @default -- See values.yaml
persistence:
  data:
    enabled: false
    type: pvc
    mountPath: "/danbooru/public/data"
    accessMode: ReadWriteOnce
    size: 10Gi

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configuration for the cron task
# @default -- See values.yaml
cron:
  enabled: true

  args: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/rails danbooru:cron"]

  controllerLabels: {}
  controllerAnnotations: {}
  podAnnotations: {}

  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}

# -- Configuration for the jobs task
# @default -- See values.yaml
jobs:
  enabled: true

  args: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/good_job start"]

  controllerLabels: {}
  controllerAnnotations: {}
  podAnnotations: {}

  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
