{{- if and .Values.persistence.enabled ( not .Values.persistence.existingClaim ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "podsync.fullname" . }}
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeMode: Filesystem
{{- end }}
