apiVersion: v1
kind: Service
metadata:
  name: {{ include "podsync.fullname" . }}
  labels:
    {{- include "podsync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "podsync.selectorLabels" . | nindent 4 }}
