{{- include "common.values.setup" . -}}
{{- if .Values.jobs.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-jobs" (include "common.names.fullname" .) | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.jobs.controllerLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.jobs.controllerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-jobs" (include "common.names.name" .) | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      {{- with .Values.jobs.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ printf "%s-jobs" (include "common.names.name" .) | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ printf "%s-jobs" (include "common.names.name" .) | quote }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.jobs.command }}
          command:
            {{- if kindIs "string" . }}
            - {{ . }}
            {{- else }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.jobs.args }}
          args:
            {{- if kindIs "string" . }}
            - {{ . }}
            {{- else }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- range $k, $v := . }}
              {{- $name := $k }}
              {{- $value := $v }}
              {{- if kindIs "int" $name }}
                {{- $name = required "environment variables as a list of maps require a name field" $value.name }}
              {{- end }}
            - name: {{ quote $name }}
              {{- if kindIs "map" $value -}}
                {{- if hasKey $value "value" }}
                  {{- $value = $value.value -}}
                {{- else if hasKey $value "valueFrom" }}
                  {{- dict "valueFrom" $value.valueFrom | toYaml | nindent 14 }}
                {{- else }}
                  {{- dict "valueFrom" $value | toYaml | nindent 14 }}
                {{- end }}
              {{- end }}
              {{- if not (kindIs "map" $value) }}
                {{- if kindIs "string" $value }}
                  {{- $value = tpl $value $ }}
                {{- end }}
              value: {{ quote $value }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if or .Values.envFrom .Values.secret }}
          envFrom:
            {{- with .Values.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.secret }}
            - secretRef:
                name: {{ include "common.names.fullname" . }}
            {{- end }}
          {{- end }}
          {{- with .Values.jobs.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.jobs.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
